cpufreq: p1022ds: of_machine_is_compatible instead of machine_is_compatible
This is a compile error fixing.  The error message is as below
arch/powerpc/platforms/85xx/cpufreq.c: In function 'mpc85xx_cpufreq_init':
arch/powerpc/platforms/85xx/cpufreq.c:221: error: implicit declaration of function 'machine_is_compatible'

Signed-off-by: Jin Qing <b24347@freescale.com>