p1022ds: fix compile error caused by renaming lmb to memblock
The compile error is as below
arch/powerpc/platforms/85xx/p1022_ds.c:20: fatal error: linux/lmb.h: No such file or directory

Signed-off-by: Jin Qing <b24347@freescale.com>